### ISSUE TITLE
merge_annotations AttributeError: 'float' object has no attribute 'split'

### ISSUE THREAD

**Issue by maia-munteanu** [PMBio/deeprvat#143]
Hi there!

Thank you for developing this tool!
I am bumping into an error when trying to run the annotations pipeline. I am running with the example files given which have been previously preprocessed. The issue seems to be coming from the merge_annotations rule, more specifically the calculate_scores_max function being run on the vep_file["SpliceAI_pred"] column. 
This is the error message:

```
[Mon Oct 21 14:07:04 2024]
rule merge_annotations:
    input: output_dir/annotations/test_vcf_data_c21_b1_vep_anno.tsv, output_dir/annotations/test_vcf_data_c21_b1_variants.parclip_deepripe.csv.gz, output_dir/annotations/test_vcf_data_c21_b1_variants.eclip_k5_deepripe.csv.gz, output_dir/annotations/test_vcf_data_c21_b1_variants.eclip_hg2_deepripe.csv.gz, ../preprocess_2/workdir/norm/variants/variants.parquet, output_dir/annotations/tmp/test_vcf_data_c21_b1_variants.vcf, ../../example/config/annotation_colnames_filling_values.yaml
    output: output_dir/annotations/test_vcf_data_c21_b1_merged.parquet
    jobid: 94
    reason: Missing output files: output_dir/annotations/test_vcf_data_c21_b1_merged.parquet
    wildcards: file_stem=test_vcf_data_c21_b1
    resources: tmpdir=/local_scratch/tmp, mem_mb=10000

/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/dask/dataframe/utils.py:369: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)
/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/dask/dataframe/utils.py:369: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)
/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/dask/dataframe/utils.py:369: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)
Traceback (most recent call last):
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/bin/deeprvat_annotations", line 33, in <module>
    sys.exit(load_entry_point('deeprvat', 'console_scripts', 'deeprvat_annotations')())
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/deeprvat/annotations/annotations.py", line 1666, in merge_annotations
    vep_df = process_vep(
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/deeprvat/annotations/annotations.py", line 1786, in process_vep
    vep_file["SpliceAI_delta_score"] = vep_file["SpliceAI_pred"].apply(
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/core/apply.py", line 1123, in apply
    return self.apply_standard()
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/core/apply.py", line 1174, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/deeprvat/annotations/annotations.py", line 1177, in calculate_scores_max
    values = [float(score) for score in scores.split("|")[1:5] if score != "nan"]
AttributeError: 'float' object has no attribute 'split'
[Mon Oct 21 14:07:21 2024]
Error in rule merge_annotations:
    jobid: 94
    output: output_dir/annotations/test_vcf_data_c21_b1_merged.parquet
    shell:
        HEADER=$(grep  -n  '#Uploaded_variation' output_dir/annotations/test_vcf_data_c21_b1_vep_anno.tsv| head | cut -f 1 -d ':') && deeprvat_annotations merge-annotations $(($HEADER-1)) output_dir/annotations/test_vcf_data_c21_b1_vep_anno.tsv output_dir/annotations/test_vcf_data_c21_b1_variants.parclip_deepripe.csv.gz output_dir/annotation
s/test_vcf_data_c21_b1_variants.eclip_hg2_deepripe.csv.gz output_dir/annotations/test_vcf_data_c21_b1_variants.eclip_k5_deepripe.csv.gz ../preprocess_2/workdir/norm/variants/variants.parquet output_dir/annotations/tmp/test_vcf_data_c21_b1_variants.vcf output_dir/annotations/test_vcf_data_c21_b1_merged.parquet ../../example/config/annotation_
colnames_filling_values.yaml
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-21T140652.246464.snakemake.log
```

The content of the vep_anno.tsv file is:
```
## ENSEMBL VARIANT EFFECT PREDICTOR v110.1
## Output produced at 2024-10-18 20:20:12
## Using cache in repo_dir/ensembl-vep/cache/homo_sapiens/110_GRCh38
## Using API version 110, DB version ?
## ensembl-io version 110.b1a0d57
## ensembl-variation version 110.d34d25e
## ensembl-funcgen version 110.24e6da6
## ensembl version 110.584a8f3
## 1000genomes version phase3
## ClinVar version 202301
## COSMIC version 97
## gnomADe version r2.1.1
## polyphen version 2.2.3
## assembly version GRCh38.p14
## dbSNP version 154
## genebuild version 2014-07
## sift version 6.2.1
## gencode version GENCODE 44
## HGMD-PUBLIC version 20204
## gnomADg version v3.1.2
## regbuild version 1.0
## Column descriptions:
## Uploaded_variation : Identifier of uploaded variant
## Location : Location of variant in standard coordinate format (chr:start or chr:start-end)
## Allele : The variant allele used to calculate the consequence
## Gene : Stable ID of affected gene
## Feature : Stable ID of feature
## Feature_type : Type of feature - Transcript, RegulatoryFeature or MotifFeature
## Consequence : Consequence type
## cDNA_position : Relative position of base pair in cDNA sequence
## CDS_position : Relative position of base pair in coding sequence
## Protein_position : Relative position of amino acid in protein
## Amino_acids : Reference and variant amino acids
## Codons : Reference and variant codon sequence
## Existing_variation : Identifier(s) of co-located known variants
## IMPACT : Subjective impact classification of consequence type
## DISTANCE : Shortest distance from variant to transcript
## STRAND : Strand of the feature (1/-1)
## FLAGS : Transcript quality flags
## BIOTYPE : Biotype of transcript or regulatory feature
## CANONICAL : Indicates if transcript is canonical for this gene
## ENSP : Protein identifer
## SIFT : SIFT prediction and/or score
## PolyPhen : PolyPhen prediction and/or score
## SpliceAI_pred : SpliceAI predicted effect on splicing. These include delta scores (DS) and delta positions (DP) for acceptor gain (AG), acceptor loss (AL), donor gain (DG), and donor loss (DL). Format: SYMBOL|DS_AG|DS_AL|DS_DG|DS_DL|DP_AG|DP_AL|DP_DG|DP_DL
## Condel : Consensus deleteriousness score for an amino acid substitution based on SIFT and PolyPhen-2
## VEP command-line: vep --assembly GRCh38 --biotype --cache --canonical --database 0 --dir_cache [PATH]/cache --dir_plugins [PATH]/Plugins --fasta [PATH]/GRCh38.primary_assembly.genome.fa --force_overwrite --fork 5 --format vcf --input_file [PATH]/test_vcf_data_c21_b1_stripped.vcf.gz --no_escape --no_stats --offline --output_file [PATH]/test_vcf_data_c21_b1_vep_anno.tsv --per_gene --pick_order biotype,mane_select,mane_plus_clinical,canonical,appris,tsl,ccds,rank,length,ensembl,refseq --plugin [PATH]/AlphaMissense_hg38.tsv.gz --polyphen s --protein --sift s --tab --total_length
#Uploaded_variation     Location        Allele  Gene    Feature Feature_type    Consequence     cDNA_position   CDS_position    Protein_position        Amino_acids     Codons  Existing_variation      IMPACT  DISTANCE        STRAND  FLAGS   BIOTYPE CANONICAL       ENSP    SIFT    PolyPhen        SpliceAI_pred   Condel
chr21_5033887_G_A       21:5033887      A       -       -       -       intergenic_variant      -       -       -       -       -       -       MODIFIER        -       -       -       -       -       -       -       -       -       -
chr21_5038298_A_G       21:5038298      G       -       -       -       intergenic_variant      -       -       -       -       -       -       MODIFIER        -       -       -       -       -       -       -       -       -       -
chr21_5051437_C_A       21:5051437      A       -       -       -       intergenic_variant      -       -       -       -       -       -       MODIFIER        -       -       -       -       -       -       -       -       -       -
chr21_5051474_T_A       21:5051474      A       -       -       -       intergenic_variant      -       -       -       -       -       -       MODIFIER        -       -       -       -       -       -       -       -       -       -
chr21_5052251_C_A       21:5052251      A       -       -       -       intergenic_variant      -       -       -       -       -       -       MODIFIER        -       -       -       -       -       -       -       -       -       -
chr21_5053701_T_A       21:5053701      A       -       -       -       intergenic_variant      -       -       -       -       -       -       MODIFIER        -       -       -       -       -       -       -       -       -       -
chr21_10413724_C_T      21:10413724     T       ENSG00000290523 ENST00000470054 Transcript      non_coding_transcript_exon_variant      193/1891        -       -       -       -       -       MODIFIER        -       1       -       lncRNA  YES     -       -       -       -       -
```

And this is the content of the config file I am using:
```
#bcftools_load_cmd : module load bcftools/1.9
#htslib_load_cmd : module load htslib/1.9
#perl_load_cmd : module load perl/5.20.2
#vep_load_cmd : module load vep/108.1
fasta_dir : reference
fasta_file_name : GRCh38.primary_assembly.genome.fa
gtf_file_name : gencode.v44.annotation.gtf.gz

source_variant_file_pattern : test_vcf_data_c{chr}_b{block}
source_variant_file_type: 'bcf'

included_chromosomes : ['21','22']
annotation_columns_yaml_file: ../../example/config/annotation_colnames_filling_values.yaml

source_variant_dir : ../preprocess_2/workdir/norm/bcf
anno_tmp_dir : output_dir/annotations/tmp
anno_dir : output_dir/annotations

vep_cache_dir : repo_dir/ensembl-vep/cache/
vep_plugin_dir : repo_dir/ensembl-vep/Plugins
deeprvat_repo_dir : ../..
kipoiveff_repo_dir : repo_dir/kipoi-veff2
faatpipe_repo_dir : repo_dir/faatpipe
vep_repo_dir : repo_dir/ensembl-vep
preprocessing_workdir : ../preprocess_2/workdir
additional_vep_plugin_cmds:
  #cadd : CADD,annotation_data/cadd/whole_genome_SNVs.tsv.gz,annotation_data/cadd/gnomad.genomes.r3.0.indel.tsv.gz
  cadd : CADD,annotation_data/cadd/hg38/whole_genome_SNVs.tsv.gz,annotation_data/cadd/hg38/gnomad.genomes.r3.0.indel.tsv.gz
  spliceAI : SpliceAI,snv=annotation_data/spliceAI/spliceai_scores.raw.snv.hg38.vcf.gz,indel=annotation_data/spliceAI/spliceai_scores.raw.indel.hg38.vcf.gz
  #primateAI : PrimateAI,annotation_data/primateAI/PrimateAI_scores_v0.2_GRCh38_sorted.tsv.bgz
  primateAI : PrimateAI,annotation_data/primateAI/PrimateAI_scores_v0.2_hg38.tsv.gz
  condel: Condel,repo_dir/ensembl-vep/Plugin/config/Condel/config,s,2
  alphamissense : AlphaMissense,file=annotation_data/AlphaMissense/AlphaMissense_hg38.tsv.gz

#include_absplice : False

deepsea_pca_n_components : 14
```

Many thanks,
Maia

**Comment by Marcel-Mueck** [comment]
Hallo Maia, 
thank you for bringing this up, we could replicate the error based on your description and created a PR (#144) for this. We will merge the PR into main soon. 
Regards,
Marcel

**Comment by meyerkm** [comment]
Maia, since your above message, an additional update has been made to catch a wider test case regarding this bug. That has now been committed to that PR and the PR has been merged into main. 

Please reach out if any other problems arise!
