### ISSUE TITLE
rule mmsplice_splicemap - tensorflow issue

### ISSUE THREAD

**Issue by maia-munteanu** [PMBio/deeprvat#146]
Hi there!

I have stumbled upon another issue in trying to run the annotations pipeline on the example data and I was wondering if you could help. 

The error:

```
rule mmsplice_splicemap:
    input: output_dir/annotations/tmp/test_vcf_data_c22_b1_variants_header.vcf.gz, output_dir/annotations/tmp/absplice/GRCh38.primary_assembly.genome.fa, output_dir/annotations/tmp/absplice/splicemap_hg38/Adipose_Subcutaneous_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Adipose_Visceral_Omentum_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Adrenal_Gland_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Artery_Aorta_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Artery_Coronary_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Artery_Tibial_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Amygdala_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Anterior_cingulate_cortex_BA24_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Caudate_basal_ganglia_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Cerebellar_Hemisphere_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Cerebellum_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Cortex_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Frontal_Cortex_BA9_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Hippocampus_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Hypothalamus_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Nucleus_accumbens_basal_ganglia_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Putamen_basal_ganglia_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Spinal_cord_cervical_c_1_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Substantia_nigra_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Breast_Mammary_Tissue_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Cells_Cultured_fibroblasts_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Cells_EBV_transformed_lymphocytes_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Colon_Sigmoid_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Colon_Transverse_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Esophagus_Gastroesophageal_Junction_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Esophagus_Mucosa_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Esophagus_Muscularis_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Heart_Atrial_Appendage_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Heart_Left_Ventricle_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Kidney_Cortex_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Liver_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Lung_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Minor_Salivary_Gland_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Muscle_Skeletal_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Nerve_Tibial_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Ovary_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Pancreas_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Pituitary_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Prostate_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Skin_Not_Sun_Exposed_Suprapubic_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Skin_Sun_Exposed_Lower_leg_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Small_Intestine_Terminal_Ileum_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Spleen_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Stomach_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Testis_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Thyroid_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Uterus_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Vagina_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Whole_Blood_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Adipose_Subcutaneous_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Adipose_Visceral_Omentum_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Adrenal_Gland_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Artery_Aorta_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Artery_Coronary_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Artery_Tibial_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Amygdala_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Anterior_cingulate_cortex_BA24_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Caudate_basal_ganglia_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Cerebellar_Hemisphere_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Cerebellum_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Cortex_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Frontal_Cortex_BA9_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Hippocampus_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Hypothalamus_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Nucleus_accumbens_basal_ganglia_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Putamen_basal_ganglia_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Spinal_cord_cervical_c_1_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Brain_Substantia_nigra_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Breast_Mammary_Tissue_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Cells_Cultured_fibroblasts_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Cells_EBV_transformed_lymphocytes_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Colon_Sigmoid_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Colon_Transverse_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Esophagus_Gastroesophageal_Junction_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Esophagus_Mucosa_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Esophagus_Muscularis_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Heart_Atrial_Appendage_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Heart_Left_Ventricle_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Kidney_Cortex_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Liver_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Lung_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Minor_Salivary_Gland_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Muscle_Skeletal_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Nerve_Tibial_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Ovary_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Pancreas_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Pituitary_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Prostate_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Skin_Not_Sun_Exposed_Suprapubic_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Skin_Sun_Exposed_Lower_leg_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Small_Intestine_Terminal_Ileum_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Spleen_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Stomach_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Testis_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Thyroid_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Uterus_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Vagina_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz, output_dir/annotations/tmp/absplice/splicemap_hg38/Whole_Blood_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz
    output: output_dir/annotations/tmp/absplice/hg38/model_scores_from_absplice_features/test_vcf_data_c22_b1_MMSplice_SpliceMap.csv
    jobid: 90
    reason: Missing output files: output_dir/annotations/tmp/absplice/hg38/model_scores_from_absplice_features/test_vcf_data_c22_b1_MMSplice_SpliceMap.csv
    wildcards: genome=hg38, file_stem=test_vcf_data_c22_b1
    resources: tmpdir=/tmp, mem_mb=30000, threads=4

Activating conda environment: .snakemake/conda/a915feee8803afeaf2a7fb1d6e14ddd9_
Activating conda environment: .snakemake/conda/a915feee8803afeaf2a7fb1d6e14ddd9_
Traceback (most recent call last):
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/example/annotations/.snakemake/scripts/tmp_uw3oi_c.mmsplice_splicemap.py", line 5, in <module>
    from absplice import SpliceOutlier, SpliceOutlierDataloader
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/example/annotations/.snakemake/conda/src/absplice/absplice/__init__.py", line 1, in <module>
    from absplice.cat_dataloader import CatInference
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/example/annotations/.snakemake/conda/src/absplice/absplice/cat_dataloader.py", line 2, in <module>
    from absplice.dataloader import SpliceMapMixin
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/example/annotations/.snakemake/conda/src/absplice/absplice/dataloader.py", line 10, in <module>
    from mmsplice.junction_dataloader import JunctionPSI5VCFDataloader, \
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/example/annotations/.snakemake/conda/a915feee8803afeaf2a7fb1d6e14ddd9_/lib/python3.8/site-packages/mmsplice/__init__.py", line 7, in <module>
    from tensorflow.keras.models import load_model
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/example/annotations/.snakemake/conda/a915feee8803afeaf2a7fb1d6e14ddd9_/lib/python3.8/site-packages/tensorflow/__init__.py", line 436, in <module>
    _ll.load_library(_main_dir)
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/example/annotations/.snakemake/conda/a915feee8803afeaf2a7fb1d6e14ddd9_/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 153, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN3tsl7strings21FastInt32ToBufferLeftEiPc
[Tue Oct 29 11:23:33 2024]
Error in rule mmsplice_splicemap:
    jobid: 90
    output: output_dir/annotations/tmp/absplice/hg38/model_scores_from_absplice_features/test_vcf_data_c22_b1_MMSplice_SpliceMap.csv
    conda-env: /g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/example/annotations/.snakemake/conda/a915feee8803afeaf2a7fb1d6e14ddd9_

RuleException:
CalledProcessError in line 41 of /g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/pipelines/annotations/../resources/absplice_splicing_pred_DNA.snakefile:
Command 'source /opt/anaconda3/bin/activate '/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/example/annotations/.snakemake/conda/a915feee8803afeaf2a7fb1d6e14ddd9_'; set -euo pipefail;  python /g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/example/annotations/.snakemake/scripts/tmp_uw3oi_c.mmsplice_splicemap.py' returned non-zero exit status 1.
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/pipelines/annotations/../resources/absplice_splicing_pred_DNA.snakefile", line 41, in __rule_mmsplice_splicemap
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-29T112217.596852.snakemake.log
```

I am running the pipeline with the commands:
```
micromamba activate /g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations
snakemake -j 1 -s ../../pipelines/annotations.snakefile --configfile deeprvat_annotation_config.yaml --use-conda --conda-frontend conda
```

And the content of the config file is:

```
#bcftools_load_cmd : module load bcftools/1.9
#htslib_load_cmd : module load htslib/1.9
#perl_load_cmd : module load perl/5.20.2
#vep_load_cmd : module load vep/108.1
fasta_dir : reference
fasta_file_name : GRCh38.primary_assembly.genome.fa
gtf_file_name : gencode.v44.annotation.gtf.gz

source_variant_file_pattern : test_vcf_data_c{chr}_b{block}
source_variant_file_type: 'bcf'

included_chromosomes : ['21','22']
annotation_columns_yaml_file: ../../example/config/annotation_colnames_filling_values.yaml

source_variant_dir : ../preprocess_2/workdir/norm/bcf
anno_tmp_dir : output_dir/annotations/tmp
anno_dir : output_dir/annotations

vep_cache_dir : repo_dir/ensembl-vep/cache/
vep_plugin_dir : repo_dir/ensembl-vep/Plugins
deeprvat_repo_dir : ../..
kipoiveff_repo_dir : repo_dir/kipoi-veff2
faatpipe_repo_dir : repo_dir/faatpipe
vep_repo_dir : repo_dir/ensembl-vep
preprocessing_workdir : ../preprocess_2/workdir
additional_vep_plugin_cmds:
  #cadd : CADD,annotation_data/cadd/whole_genome_SNVs.tsv.gz,annotation_data/cadd/gnomad.genomes.r3.0.indel.tsv.gz
  cadd : CADD,annotation_data/cadd/hg38/whole_genome_SNVs.tsv.gz,annotation_data/cadd/hg38/gnomad.genomes.r3.0.indel.tsv.gz
  spliceAI : SpliceAI,snv=annotation_data/spliceAI/spliceai_scores.raw.snv.hg38.vcf.gz,indel=annotation_data/spliceAI/spliceai_scores.raw.indel.hg38.vcf.gz
  #primateAI : PrimateAI,annotation_data/primateAI/PrimateAI_scores_v0.2_GRCh38_sorted.tsv.bgz
  primateAI : PrimateAI,annotation_data/primateAI/PrimateAI_scores_v0.2_hg38.tsv.gz
  condel: Condel,repo_dir/ensembl-vep/Plugin/config/Condel/config,s,2
  alphamissense : AlphaMissense,file=annotation_data/AlphaMissense/AlphaMissense_hg38.tsv.gz

#include_absplice : False

deepsea_pca_n_components : 14

```

As far as I can tell the absplice conda environment is being built correctly, but there is some issue with tensorflow, perhaps because of the difference in tensorflow version between the deeprvat_annotations and absplice environments?

**Comment by Marcel-Mueck** [comment]
Hello Maia, 
this seems to be a problem with the particular tensorflow version. One way to resolve this  (which we tried successfully)  is to delete the `libtfkernel_sobol_op.so` and rerun.

**Comment by maia-munteanu** [comment]
Thanks a lot! Deleting that seems to have fixed the issue with the mmsplice_splicemap rule. 
However, there seems to be a new one in the merge_allele_frequency rule, I think due to the duplication of "af_y" and "af_x" after the af_df merge, but I'm not quite sure why. The error message is below, please let me know if I should open a separate issue.

```
rule merge_allele_frequency:
    input: output_dir/annotations/tmp/af_df.parquet, output_dir/annotations/chckpts/merge_absplice_scores.chckpt, output_dir/annotations/chckpts/merge_deepsea_pcas.chckpt, output_dir/annotations/chckpts/concat_annotations.chckpt
    output: output_dir/annotations/chckpts/merge_allele_frequency.chckpt
    jobid: 7
    reason: Input files updated by another job: output_dir/annotations/chckpts/merge_absplice_scores.chckpt
    resources: tmpdir=/tmp, mem_mb=30000

/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/dask/dataframe/utils.py:369: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)
/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/dask/dataframe/utils.py:369: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)
/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/dask/dataframe/utils.py:369: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)
/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/deeprvat/annotations/annotations.py:1945: FutureWarning: Passing 'suffixes' which cause duplicate columns {'af_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_df = annotations_df.merge(af_df, how="left", on="id")
Traceback (most recent call last):
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/bin/deeprvat_annotations", line 33, in <module>
    sys.exit(load_entry_point('deeprvat', 'console_scripts', 'deeprvat_annotations')())
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/g/strcombio/fsupek_cancer3/SV_clusters_project/Germline/deeprvat/deeprvat/annotations/annotations.py", line 1946, in merge_af
    merged_df.to_parquet(out_file)
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/core/frame.py", line 2976, in to_parquet
    return to_parquet(
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/io/parquet.py", line 430, in to_parquet
    impl.write(
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/pandas/io/parquet.py", line 174, in write
    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
  File "pyarrow/table.pxi", line 3557, in pyarrow.lib.Table.from_pandas
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/pyarrow/pandas_compat.py", line 570, in dataframe_to_arrays
    convert_fields) = _get_columns_to_convert(df, schema, preserve_index,
  File "/g/strcombio/fsupek_home/mmunteanu/tools/miniforge3/envs/deeprvat_annotations/lib/python3.9/site-packages/pyarrow/pandas_compat.py", line 352, in _get_columns_to_convert
    raise ValueError(
ValueError: Duplicate column names found: ['Consequence_frameshift_variant', 'QKI_parclip', 'Consequence_splice_donor_variant', 'Consequence_splice_acceptor_variant', 'MBNL1_parclip', 'QKI_k5', 'HNRNPD_parclip', 'Consequence_stop_gained', 'TARDBP_parclip', '
Consequence_splice_region_variant', 'Condel', 'CADD_PHRED', 'Consequence_inframe_deletion', 'KHDRBS1_k5', 'SIFT', 'Consequence_inframe_insertion', 'PolyPhen', 'am_pathogenicity', 'QKI_hg2', 'Consequence_protein_altering_variant', 'SpliceAI_delta_score', 'Con
sequence_missense_variant', 'CADD_RAW', 'Consequence_start_lost', 'ELAVL1_parclip', 'Consequence_stop_lost', 'chrom', 'pos', 'ref', 'alt', 'id', 'gene_base', 'DeepSEA_PC_3', 'DeepSEA_PC_5', 'DeepSEA_PC_2', 'DeepSEA_PC_6', 'DeepSEA_PC_4', 'DeepSEA_PC_1', 'af_
x', 'maf', 'maf_mb', 'Gene', 'is_plof', 'af_y', 'af_x', 'AbSplice_DNA', 'af_y']
[Wed Oct 30 12:57:57 2024]
Error in rule merge_allele_frequency:
    jobid: 7
    output: output_dir/annotations/chckpts/merge_allele_frequency.chckpt
    shell:
        deeprvat_annotations merge-af output_dir/annotations/annotations.parquet output_dir/annotations/tmp/af_df.parquet output_dir/annotations/annotations.parquet && touch output_dir/annotations/chckpts/merge_allele_frequency.chckpt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-30T125732.772124.snakemake.log
```

Many thanks,
Maia

**Comment by maia-munteanu** [comment]
I think this was actually caused by re-running parts of the pipeline which add columns to the annotations file, no issues when re-running from scratch.

**Comment by Marcel-Mueck** [comment]
Hello Maia, thank you for the update. If anythng else pops up, don't hesitate to contact us :) 
Regards, deeprvat dev team
